name: Build the DotNet Solution

on:
  workflow_call:
    inputs:
      buildConfiguration:
        required: true
        type: string
    
jobs:
  build-dotnet:
    name: Build the .NET Solution
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup MSBuild path
      uses: microsoft/setup-msbuild@v1.1
      with:
          dotnet-version: 8.0.0
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.6
    - name: Restore NuGet packages
      run: nuget restore src\Hackathonn.sln
    - name: Build
      run: msbuild src\Hackathonn.sln /p:Configuration=${{ inputs.buildConfiguration }}