name: CI-CD - hackathonUSA 24 - STORYBOOK
on: 
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/CI-CD_hackathonUSA_24_STORYBOOK.yml
      - .github/workflows/build_NextJs.yml
      - .github/workflows/deploy_vercel.yml
      - 'src/Project/hackathonUSA2024/hackathonUSA/**'
  pull_request:
    branches: [ main ]
    paths:
      - .github/workflows/CI-CD_hackathonUSA_24_STORYBOOK.yml
      - .github/workflows/build_NextJs.yml
      - .github/workflows/deploy_vercel.yml
      - 'src/Project/hackathonUSA2024/hackathonUSA/**'

jobs:

  build-hackathonUSA24-storybook:
    if: github.ref != 'refs/heads/main'
    uses: ./.github/workflows/build_NextJs_Storybook.yml
    with:
      workingDirectory: ./src/Project/hackathonUSA2024/hackathonUSA

  deploy-hackathonUSA24-storybook:
    uses: ./.github/workflows/deploy_vercel.yml
    needs: build-hackathonUSA24-storybook
    if: always() && 
        (github.repository_owner == 'Sitecore' && ((github.event.pull_request.head.repo.full_name == github.repository) || (github.event_name == 'push'))) &&
        needs.build-hackathonUSA24-storybook.result != 'failure' &&
        needs.build-hackathonUSA24-storybook.result != 'cancelled'
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_hackathonUSA_24_STORYBOOK_PROJECT_ID }}